### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by Slater-Victoroff** [alecxe/scrapy-fake-useragent#13]
This library now errors whenever it's being used because the SSL certificate on the herokuapp is expired.

Traceback below: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 45, in get
    return urlopen(request, timeout=settings.HTTP_TIMEOUT).read()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```

**Comment by alecxe** [comment]
@Slater-Victoroff this library is a very thin wrapper around the `fake-useragent`, please address the problem at the [library's issue tracker](https://github.com/hellysmile/fake-useragent/issues) if it is still reproducible and was not a temporary problem. Thanks!
