### ISSUE TITLE
Heroku Application Broken

### ISSUE THREAD

**Issue by james-innes** [alecxe/scrapy-fake-useragent#38]
Heroku has terminated their free tier.

I am making the assumption this is why the application at this address is broken:
[https://fake-useragent.herokuapp.com/browsers/0.1.11](https://fake-useragent.herokuapp.com/browsers/0.1.11)

```log
2022-12-03 19:29:40 [fake_useragent] WARNING: Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
```

**Comment by james-innes** [comment]
The has been picked up in the parent package `fake-useragent` in [this issue](https://github.com/fake-useragent/fake-useragent/issues/158#issue-1469766653) and was resolved for me buy running `pip install --upgrade fake-useragent`

**Comment by Cuestax** [comment]
Thanks a lot
